application: kohlivarun5
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /google7e073e6fd0855e04.html
  static_files: static/google7e073e6fd0855e04.html 
  upload: noop

- url: /favicon.ico
  static_files: static/images/favicon.ico 
  upload: static/images/favicon\.ico

- url: /apple-touch-icon.png
  static_files: static/images/main_icon.png 
  upload: noop

- url: /images
  static_dir: static/images/ 

- url: /robots.txt
  static_files: static/robots.txt 
  upload: static/robots.txt

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: main.app
  secure: always

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^.*\.pyc$
